services:
  - type: web
    name: plantdoc-flask-app
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app1:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
